name: Fiscoin
version: ${project.version}
main: dev.vrba.minecraft.fiscoin.Fiscoin
api-version: 1.16
authors: [ 0x4a69726b61 ]
description: Cryptocurrency blockchain mod where Proof Of Work (mining) is implemented by mining blocks
commands:
  blockchain:
    description: View the current blockchain state and blocks
  wallet:
    description: Loads or generates player's crypto wallet